Add Link and Profanity filtering
BTE-Germany/BTEDE-Discord-Bot pull request #1
Opened 2022-02-12 17:55 UTC by Mic-R

2022-02-12 17:57 UTC, Mic-R commented
@Nachwahl @Le4nderS 
Everything here is as we already told about, please test before merging!

2022-02-13 15:04 UTC, Qreepex commented on src/events/message.js
> +                //moderate links and bad words
Muss an eine andere Stelle, ist aktuell mitten im Bewerbungskram drin, wird also nicht funktionieren

2022-02-13 15:07 UTC, Qreepex requested changes
Muss an eine andere Stelle im Message Event, ist aktuell mitten im Bewerbungskram drin.

2022-02-13 15:15 UTC, Mic-R commented
Habe es jetzt mal überarbeitet, sollte so stimmen. Wenn ich es noch irgendwo reinhab bitte melden, denke aber das ist die Richtige Position.

2022-02-13 18:07 UTC, robinferch requested changes
Looks good so far, but you should consider switching to regex for the url checks to prevent users from get around the protection

2022-02-13 18:09 UTC, Mic-R commented
> Looks good so far, but you should consider switching to regex for the url checks to prevent users from get around the protection

Ok, I will be doing that, but in the next change i will be pushing out with the tiktok/twitta/etc. api update

2022-02-13 18:16 UTC, Qreepex approved these changes
Looks good

2022-02-13 18:17 UTC, robinferch commented
> > Looks good so far, but you should consider switching to regex for the url checks to prevent users from get around the protection
> 
> Ok, I will be doing that, but in the next change i will be pushing out with the tiktok/twitta/etc. api update

Please do that in a seperate PR

2022-02-13 18:18 UTC, Mic-R commented
> requested

That was my plan anyways!

2022-02-13 18:28 UTC, Nachwahl approved these changes

2022-02-13 18:28 UTC, merged